### ISSUE TITLE
Fails to work

### ISSUE THREAD

**Issue by RyanRoberts** [RayPS/Link-Text-Selector#1]
[update] OK so restarting Safari got the extension working 🙄😆

Nice idea with the extension, but unfortunately it doesn't appear to work at all for me. The keys used are already assigned to other functions by Safari, would to be possible for you to add the ability to choose your own keys?

There's no much info I can give on the problem though, I hover my mouse cursor over a link and press shift (or any of the others once changed in preferences), nothing happens.

**Comment by RayPS** [comment]
That's weird, it should be working without restarting Safari. Only a page refresh is required.
Are you using the extension by installing the App from Mac App Store or just the .safariextz  file?
Btw. You can change the shortcut key in both ways.

**Comment by RyanRoberts** [comment]
It was the App Store version.
